mysql:
  host: localhost
  port: 3306
  database: points
  user: root
  password: password
points:
  start_value: 500
language:
  prefix: "&7[&aPoints&7] "
  player_not_found: "&7Player &c%player% &7not found."
  points_self: "&7You have &a%points% &7points."
  points_others: "&2%player% has &a%points% &7points."
  player_points_set: "&7Points of &2%player% &7has been set to &a%amount%"
  player_points_removed: "&2%amount% &7removed from &2%player%'s &7Points."
  player_points_added: "&a%amount% &7added to &2%player%'s &7Points."