name: PointsAPI
version: '1.2.6-STABLE'
main: dev.teraprath.points.Main
api-version: 1.19
authors: [ TerryGHG ]
commands:
  points:
    description: Show your points
    permission: points.show
  apoints:
    description: Admin Command
    aliases:
      - ap
    permission: points.admin
